
export default class Coach{

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Constructor for coach class that includes the class dependencies
     * @param {Object} reasoner The singleton instance of the reasoner class to provide AI content
     * @param {Object} service The singleton instance of user services to acccess player data
     */
    constructor(reasoner,service) {
        this.reasoner = reasoner;//gemini api wrapper class/object
        this.userservice = service;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    async get_suggestions_by_activity(activity_id,character) {
        return await this.reasoner.act_build(
            activity_id,
            this.userservice.getUserItems(this.getDisplayName()),
            character
        );
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    async getWeaponSkillsContent(statType){
        const stats = await this.userservice.getWeaponStats(this.getDisplayName(), true);
        const content = await this.reasoner.weaponSkills(
            stats
        );
        return content;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    async getCharacterAnalysis(characterid){
        const configuration = await this.userservice.getCharacterConfiguration(this.getDisplayName(),characterid);
        const content = await this.reasoner.characterAnalysis(configuration);
        return content;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Method to fetch from user service the players most recent activities
     * @param {string} characterid The character to fetch the recent activities for
     * @returns {Promise<Object>} Object of activity summaries
     */
    async getRecentActivities(characterid){

        return await this.userservice.getRecentActivities(
            this.getDisplayName(),
            characterid
        );
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Get the data by which the mentor service helps a player measure their improvement week on week
     * @returns {Promise<Object>} The data object
     */
    async getProgressionData(){
        return await this.userservice.getCoachData();
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Method to combine player game data and the reasoner to produce targets generated by the reasoner
     * @returns {Promise<Object>} An object of targets
     */
    async getGeneratedTargets(){
        return await this.reasoner.generatedTargets(
            {
                weapon: await this.userservice.getWeaponStats(this.getDisplayName(), true),
            }
        )
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Method to combine an activity summary and the reasoner to produce a coaching style analysis of a players performance
     * in an activity
     * @param {string} instanceid That maps to an activity on the bungie API
     * @param {string} characterid The character the player played as for this activity
     * @returns {Promise<Object>} The generated object from the reasoner
     */
    async getActivityAnalysis(instanceid,characterid){
        return await this.reasoner.activityAnalysis(
            await this.userservice.getActivitySummary(
                instanceid,
                characterid
            )
        )
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getDisplayName(){
        return this.details.displayname;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getCharacters(){
        return this.details.characters;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getRefreshToken(){
        return this.details.refreshToken;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getAccessToken(){
        return this.details.accessToken;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getAccessExpiry(){
        return this.details.accessExpiry;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getRefreshExpiry(){
        return this.details.refresh_expiry;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getMemberType(){
        return this.details.membertype;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getMembershipId(){
        return this.details.membershipid;
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    getCharacterIds(){
        return this.details.characters.characters[0][0];
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}